default: &default
  adapter: mysql2
  username: root

development:
  <<: *default
  database: energy_development
  host: 127.0.0.1

test:
  <<: *default
  database: energy_test

production:
  adapter: mysql2
  database: energy
  username: "<%= ENV["SQL_USER"] %>"
  password: "<%= ENV["SQL_PASSWORD"] %>"
