default: &default
  adapter: mysql2
  host: "<%= ENV["SQL_HOST"] %>"
  username: "<%= ENV["SQL_USER"] %>"
  password: "<%= ENV["SQL_PASSWORD"] %>"


development:
  <<: *default
  database: energy

test:
  <<: *default
  database: energy_test

production:
  <<: *default
  database: energy
