default: &default
  adapter: mysql2
  username: root

development:
  <<: *default
  database: energy_development

test:
  <<: *default
  database: energy_test

production:
  <<: *default
  database: energy
