default: &default
  adapter: mysql2
  username: root

development:
  <<: *default
  database: energy_development

test:
  <<: *default
  database: energy_test

production:
  adapter: mysql2
  database: energy
  username: "<%= ENV["SQL_USER"] %>"
  password: "<%= ENV["SQL_PASSWORD"] %>"
